FROM node:20-alpine AS build

WORKDIR /app

COPY client/package*.json ./
COPY client ./
COPY common ../common

WORKDIR /app
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY client/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/client /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
